[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "c8be8b87ab32eb48747cc7edf00c14fb06679afe"
hash = "167w3xymkb7fr2wxd6by3gd45rd8w6w04mal7k4qzz9widiapd5l"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "a3a1a6c664a0bb387b3ce444e08830b557f15fb6"
hash = "11d4sfw5ycnyma3piddpjl9kfvhsfvyk7d61bspf280a68h8bxpf"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "b530ddae3595042e67b17192f1894ba5abf54889"
hash = "14dd60716ha0apnj39gk0rv5gd4765h4rdpy52ng39apylxlqc0q"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

