[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "8ab51a600b71b2b5656f59df8b93182507706ecd"
hash = "0vk7kxvzwvvczy2z5p3rmy7lmxn6nbzghbxwq1isdmk238wzpzj7"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "d05ad04c6a47d1c81df132af39546bd481459d70"
hash = "1jwikn1sw589j32z039wymshysl94g8iy11nn2wm1nzq5mpjy3xq"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "b530ddae3595042e67b17192f1894ba5abf54889"
hash = "14dd60716ha0apnj39gk0rv5gd4765h4rdpy52ng39apylxlqc0q"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

