[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "13ba0ede79867ced6d309eb32fff5a00db205af3"
hash = "10d1pp6idahqrgvmfb37kacd4mh4dylbsbda6y7mgf0x7h4ga728"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "609641f8fe99fafe7e6f69441f60792fb7c51b60"
hash = "1vmbmbhssml9df8lzin1vy6wkqhdi8is3argfvmnr7yfk92n88kk"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "d91a2e9d6ed3b35bcf32001de8ec4bcd5c706d3b"
hash = "1j7ha7a04a513skii11xizh6x66jdvcaxc7dk4s3dvw27mc1lj3a"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

