[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "5ae1aac5ea4992e5c41b479907ab46b9b811b8df"
hash = "1hzw1w9cfyn07fynvmcvvl51z6j4kmb7ngx8va1n8mwn22wpbpav"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "609641f8fe99fafe7e6f69441f60792fb7c51b60"
hash = "1vmbmbhssml9df8lzin1vy6wkqhdi8is3argfvmnr7yfk92n88kk"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "b530ddae3595042e67b17192f1894ba5abf54889"
hash = "14dd60716ha0apnj39gk0rv5gd4765h4rdpy52ng39apylxlqc0q"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

