[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "2100ebc4e2e572e42a2de9d2d217c2004b874098"
hash = "0kijqgipcv9dcwnvg8br34sgp3n9kxy6r44h996pyjs3ckxfm1r0"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "609641f8fe99fafe7e6f69441f60792fb7c51b60"
hash = "1vmbmbhssml9df8lzin1vy6wkqhdi8is3argfvmnr7yfk92n88kk"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "7795f4cd902e9bcd36dc3982e5a2c0f9b5c87a0f"
hash = "15f1fxggc0vk354m2rmpvg5ziaqj1v5vgc1zkrawlbx980hh4d32"

[[talon_repos]]
owner = "chaosparrot"
repo = "talon_hud"
rev = "a2d569e8a7152a518940bb3ee25bb1f2a20d1f9e"
hash = "1jqjszfqrp0gan722fxg9kzqh46cn8vzqjpjra3b9bk8gbn4mvnb"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

