[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "90b6d2e6b3a90f1776186cb17073771872cc6738"
hash = "0h4yssy9wfyk07hzp9aqrq2wk1k86lmcbfzaabhjh0r6m3ip12q1"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "609641f8fe99fafe7e6f69441f60792fb7c51b60"
hash = "1vmbmbhssml9df8lzin1vy6wkqhdi8is3argfvmnr7yfk92n88kk"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "b797a7c1307f8cdbc4736ccf81f142f11e1bf7c2"
hash = "1v83g43ml2xrlmvj3x35npl19vygkb3c7ss56bykpj8ihzpba3lm"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

