[[talon_repos]]
owner = "talonhub"
repo = "community"
rev = "cf5807dae6b963fc23cdb682a73a5b89a4250c53"
hash = "0kaqxi4d4dpgxfg4bwh7qr76bw70vq1bmxmkcblrpwbz2q64fq1k"

[[talon_repos]]
owner = "david-tejada"
repo = "rango-talon"
rev = "609641f8fe99fafe7e6f69441f60792fb7c51b60"
hash = "1vmbmbhssml9df8lzin1vy6wkqhdi8is3argfvmnr7yfk92n88kk"

[[talon_repos]]
owner = "cursorless-dev"
repo = "cursorless-talon"
rev = "370d876024fb3458883d8302191d5761c9b5c59c"
hash = "03fqzih6nc0kqz3w0zh47mxrd73035z7vj68b25291gp82ph5hzn"

[[talon_repos]]
owner = "ProfDoof"
repo = "talon_hud"
rev = "24927057307694911c6cc3b04483d1e6f728d891"
hash = "0dw2indipjmczksb2sb33f5byb7958qk2qb1hhnv0iasy6nlk2v4"

[[talon_repos]]
owner = "ProfDoof"
repo = "speak-the-spire-talon"
rev = "dd3ede06fa736efb00ddf5fe9fded7d19a9e094d"
hash = "0caznzhc7fp3a6a6d92x3r2pmzlybdrp8bqrbxqh374ji37dfvf1"

